version: '3.3'

services:

  psql:
    image: postgres:11.12
    container_name: authorization-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgresDb
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPassword
    volumes:
      - ./docker/postgres:/var/lib/postgresql
    networks:
      - blitech-net

  redis:
    image: redis
    container_name: authorization-redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
    networks:
      - blitech-net

  localstack:
    image: localstack/localstack
    container_name: authorization-localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=secretsmanager
    volumes:
      - ./docker/localstack:/var/lib/localstack
    networks:
      - blitech-net

  create_secret:
    image: amazon/aws-cli
    container_name: authorization-create_secrets
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 20;
        aws --endpoint-url=http://localstack:4566 secretsmanager create-secret --name local/authorization/databaseUser --secret-string "postgresUser"
        aws --endpoint-url=http://localstack:4566 secretsmanager create-secret --name local/authorization/databasePassword --secret-string "postgresPassword"
        aws --endpoint-url=http://localstack:4566 secretsmanager create-secret --name local/authorization/jwtPrivateKey --secret-string "base64:MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCt03v70wgRQUGxcaiv3bfcfe3faSxBywWV0isQ50C+gdBuIVECCYc2/w/8hLxiAIKFYVgixR9zR2MD8cEBNQ+e4QEjy/RcYmBjdWdSEWoyg5v6dG0wZ7wmFcHjDKDbkI5yFqOwbGLkHEAXsej2tsW2YDQ7/Xbbfl2ky9ST1/GP9p089eBSoPLwahkp2l7Sl3Bbfvd3h6xVRQ9NEIJrWKkU6h+T4pIVXxBWWpKtvOxrke6AcgIsDz0IuG86Mtck9WDuZxEU1c3creCjcm4d4JAZaSx+a1+mIZXhyKkAl/Bepmgz/Xx1jeXZFvYk4icTLZHIaQ4CK76IiRCAcF4XEAz/AgMBAAECggEAB5hPeQPR/OsEg0vLio+d+njYHWRbhi5oOpEZx53LEufaIw26m+OtsEX5vVdRYdjS2yATOUWyp5dNaL016ScX3SHIqnc9YJH90yqsjoXrRXTBqnJO2QgXTPSzaYfCOYW565s4oLtDoOLpG//uhWUcA2l1rs9W06VUUyCC08jiKZ+S4SAv7APwuwCgHO4BkCA+d4sIrqWvsjpVU4AhAUSmQSjUrqFiees431lyAlMOFacdV+ekvlPvzBwW00SUT4TKYAuBDQ3U15MvKpVdaoC2y3LfKk9BC3WAeIUF2lbtI0if5wNdircQ/Qc1RPvydTbLRO+wJSLCIs/JBxHG1XkVjQKBgQDnQAbJPEvdO3aBx4KYpyQ9+twZt3X7qYoBJolTOkiWMfaZsuFwYVgJUk/1gvWOKDykKqKlOK/zZhhL1/izGTgBYDVH0ieuS2qRGP8ZuaJDshmK0/Znu5bNNdjPAEyTlGh79uY0s7LtUP41pQiDsD0ProMoOcLU6nxKqqdzUllxNQKBgQDAbhwZcDFY2ie/HjVmaMvf1amBpqVwfQ+I0tpIO7AOE3GXt8jYGViI/6HkqfIzEE/hx2UvoHs221xVU7U9NBhknw6wC06EpMtybZI3wBdh49T2iTT4Y4rVuOaQtF4u9ANwF8loM+BzZ6vVtwk0bOKbmsYE0h5T6LTzWm3IA4Zf4wKBgQDRdEyxOMv+Nj3AjtTbL4jEGtQA9wsGRymYoS8BE2lroRWbYUqQX5s91jBWT6faetdyWqu2uwGjlHWtPJEmp1Dy7hFUXCVU2TpM8jcdNeajKk24UQR+MIsGlB8sXzj88w8wORGJ6rnF+fZG4JQ1swubiJWDec3ezASIHMpOyef5gQKBgFMJ8RRFJvZZxdcieRbFWF0yPaCWQkRFo4N+wfVz1GhumZFIHOKsJVmRPtKHR94jRuV+fzrLPQCSLskfg1Fy/qfFP7hWWL7CwoyRngxy12RFxevRj8s0YYAS92QwgYgvgqBHk4FlCZGjhjKGdvFpn2xYoOUJq064WAW/2yn5423TAoGAFdefWEv0jjRDm+JZ0whuiCnZ5k6W5bd4VPd1L5fOfINDIB5UPR/gxKWf6L2SZX+PMgn/K/2iujDLIt91sD8gojXePRNjiz7Rr41wbZPXe9EWOsnsyMPGlEaBFKsEUpoEsIQfMMnOGxXxS+8niOOULviSSPCJdX3m8KgormQMckY="
        aws --endpoint-url=http://localstack:4566 secretsmanager create-secret --name local/authorization/jwtPublicKey --secret-string "base64:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArdN7+9MIEUFBsXGor9233H3t32ksQcsFldIrEOdAvoHQbiFRAgmHNv8P/IS8YgCChWFYIsUfc0djA/HBATUPnuEBI8v0XGJgY3VnUhFqMoOb+nRtMGe8JhXB4wyg25COchajsGxi5BxAF7Ho9rbFtmA0O/12235dpMvUk9fxj/adPPXgUqDy8GoZKdpe0pdwW373d4esVUUPTRCCa1ipFOofk+KSFV8QVlqSrbzsa5HugHICLA89CLhvOjLXJPVg7mcRFNXN3K3go3JuHeCQGWksfmtfpiGV4cipAJfwXqZoM/18dY3l2Rb2JOInEy2RyGkOAiu+iIkQgHBeFxAM/wIDAQAB"
        aws --endpoint-url=http://localstack:4566 secretsmanager create-secret --name local/authorization/ldapUser --secret-string "admin"
        aws --endpoint-url=http://localstack:4566 secretsmanager create-secret --name local/authorization/ldapPassword --secret-string "base64:YWRtaW4="
      "
    networks:
      - blitech-net

  prometheus:
    image: prom/prometheus
    container_name: authorization-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - blitech-net

  otel-collector:
    image: otel/opentelemetry-collector
    container_name: authorization-otel-collector
    ports:
      - "4318:4318"  # Porta para recepção de métricas OTLP
      - "9464:9464"  # Porta para exposição de métricas Prometheus
    command:
      - --config=/etc/otel-collector-config.yml
    volumes:
      - ./docker/opentelemetry/otel-collector-config.yml:/etc/otel-collector-config.yml
    networks:
      - blitech-net

  grafana:
    image: grafana/grafana
    container_name: authorization-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Senha padrão, altere conforme necessário
      - GF_SECURITY_ADMIN_PASSWORD_IS_SECRET=true
    volumes:
      - ./docker/grafana:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning  # Volume de provisionamento
    depends_on:
      - prometheus
    networks:
      - blitech-net

networks:
  blitech-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.18.1.0/24